version: '2'
services:
  master-rabbit:
    build: ./
    ports:
      - 8080:15672
    networks:
      rmqbr:
        ipv4_address: 172.18.1.2

  rabbit2:
    build: ./
    ports:
      - 8081:15672
    networks:
      rmqbr:
        ipv4_address: 172.18.1.3

  rabbit3:
    build: ./
    ports:
      - 8082:15672
    networks:
      rmqbr:
        ipv4_address: 172.18.1.4

networks:
  rmqbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
