version: '2.2'
services:
  master-rabbit:
    hostname: master-rabbit
    build: ./master
    ports:
      - 8080:15672
    networks:
      rmqbr:
#        ipv4_address: 172.18.1.2
#    depends_on:
#      - slave-rabbit

  slave-rabbit:
    build: ./slave
    scale: 2
    networks:
      rmqbr:
    depends_on:
      - master-rabbit


networks:
  rmqbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
